DESCRIPTION
R/brmsfit-helpers.R
R/brmsfit-methods.R
R/brmsformula.R
R/data-helpers.R
R/extract_draws.R
R/make_stancode.R
R/make_standata.R
R/misc.R
R/priors.R
R/rename.R
R/stan-helpers.R
R/stan-predictor.R
R/validate.R
man/brms-package.Rd
man/brmsformula.Rd
tests/testthat/tests.brmsfit-methods.R
tests/testthat/tests.make_stancode.R
tests/testthat/tests.make_standata.R
tests/testthat/tests.rename.R
tests/testthat/tests.validate.R

Feature issue 91

---

R/brmsformula.R
man/brmsformula.Rd

fix small typo in brmsformula documentation

---

vignettes/brms_families.Rmd

fix typo in Beta density

---

R/brmsfit-methods.R

missing \
I hope I'm doing the pull right

 fixed broken link

---

R/brmsfit-methods.R

I think [shinystan issue #155](https://github.com/stan-dev/shinystan/issues/155) can actually be fixed easier than I thought from inside brms. This PR should take care of it I believe. The trick is to not use the method for stanfit objects and instead to create the shinystan object from the relevant various components.

 Fix missing parameter problem in shinystan

---

R/brm.R

DOC: sample_prior for improper (default) priors.

---

NEWS.md
R/data-predictor.R
R/stan-helpers.R
R/stan-likelihood.R
inst/chunks/fun_normal_errorsar.stan
inst/chunks/fun_normal_lagsar.stan
inst/chunks/fun_student_t_errorsar.stan
inst/chunks/fun_student_t_lagsar.stan
tests/testthat/tests.make_stancode.R

This PR improves the efficiency of SAR models drastically as discussed in #680.
Thanks to @aslez for making this possible!

Improve efficiency of SAR models

---

vignettes/brms_customfamilies.Rmd
vignettes/brms_distreg.Rmd
vignettes/brms_families.Rmd
vignettes/brms_missings.Rmd
vignettes/brms_monotonic.Rmd
vignettes/brms_multivariate.Rmd
vignettes/brms_nonlinear.Rmd
vignettes/brms_phylogenetics.Rmd

These are all really minor and inconsequential typos, but I was reading through some of the vignettes and figured I might as well fix them.

fix a bunch of minor typos in vignettes

---

NEWS.md
R/emmeans.R
man/emmeans-brms-helpers.Rd
tests/testthat/tests.emmeans.R

This PR is a follow-up on #993 with some additional fixes. There are still some problems which need to be resolved together with @rvlenth before the PR can be merged.

Support dpar = "mean" in emmeans

---

inst/chunks/fun_asym_laplace.stan
inst/chunks/fun_cholesky_cor_ar1.stan
inst/chunks/fun_cholesky_cor_arma1.stan
inst/chunks/fun_cloglog.stan
inst/chunks/fun_com_poisson.stan
inst/chunks/fun_discrete_weibull.stan
inst/chunks/fun_hurdle_negbinomial.stan
inst/chunks/fun_inv_gaussian.stan
inst/chunks/fun_normal_errorsar.stan
inst/chunks/fun_normal_lagsar.stan
inst/chunks/fun_sparse_car_lpdf.stan
inst/chunks/fun_sparse_icar_lpdf.stan
inst/chunks/fun_student_t_errorsar.stan
inst/chunks/fun_student_t_lagsar.stan

This PR makes (very) minor updates to the Stan code snippets in ```inst/chunks```. No reparameterisations or refactoring, just updating the use of composed functions (i.e., ```log1p(x)```) for slightly improved numerical stability

Minor updates to Stan chunks (composed functions)

---

R/brm.R
man/brm.Rd

Fixes:
```
Warning: Warning: Link to unknown topic: rstan::stanmodel-method-sampling
Warning: Warning: Link to unknown topic: rstan::stanmodel-method-vb
```

man: rstan: Fix sampling and vb links

---

R/formula-gp.R

I came here to change the `~` to `\sim` in the formula, and have suggested a few other edits as well.

small edits to gp( ) docs

---

.github/workflows/R-CMD-check.yaml
.github/workflows/test-coverage.yaml
tests/testthat/tests.make_stancode.R

Add `cmdstanr` installation to workflow setup to fix dependency errors

Fix workflow failures

---

.github/workflows/R-CMD-check.yaml
.github/workflows/test-coverage.yaml

Minor updates following #1321.

GHA: Update workflows

---

DESCRIPTION
NEWS.md
R/brmsformula.R
R/families.R
R/family-lists.R
R/misc.R
R/priors.R
R/restructure.R
R/stan-likelihood.R
R/stan-predictor.R
R/stan-prior.R
R/stan-response.R
man/cs.Rd
man/mo.Rd
tests/local/tests.models_new.R
tests/testthat/tests.make_stancode.R

This PR refactors and unifies parameter boundary interfaces such that bounadries of all parameters can be changed by the user via the `prior` interface.

Refactor and unify parameter boundary interfaces

---

R/projpred.R

This should fix stan-dev/projpred#304.

Fix stan-dev/projpred#304

---

NEWS.md
R/projpred.R
man/get_refmodel.brmsfit.Rd

This PR adds support for projpred's latent projection which has just been merged into projpred's `master` branch (see stan-dev/projpred#372).

Latent projection

---

R/brmsformula.R
R/brmsterms.R
R/formula-ac.R

some minor cleaning of environment handling.

Issue 1476

---

DESCRIPTION
NEWS.md
R/brm.R
R/brmsfit-class.R
R/conditional_effects.R
R/data-predictor.R
R/make_standata.R
R/restructure.R
man/brmsfit-class.Rd

Fix issue #1465

---

DESCRIPTION

it would save a few clicks from people looking for documentation

link to rpkg site

---

R/exclude_pars.R

Fix exclude_pars.R doc

---

R/backends.R

- Replace lp_approx__ with log_g__
- Assign then return stanfit object instead of implicit return

Special casing for lp_approx__

---

R/log_lik.R

"observatio" typo

---

.gitignore
DESCRIPTION
NEWS.md
R/data-predictor.R
R/formula-gp.R
R/predictor.R
R/prepare_predictions.R
R/stan-predictor.R
inst/chunks/fun_gp_exp_quad.stan
inst/chunks/fun_gp_exponential.stan
inst/chunks/fun_gp_matern32.stan
inst/chunks/fun_gp_matern52.stan
inst/chunks/fun_spd_exp_quad.stan
inst/chunks/fun_spd_gp_exp_quad.stan
inst/chunks/fun_spd_gp_matern32.stan
inst/chunks/fun_spd_gp_matern52.stan
man/gp.Rd
tests/local/tests.models-3.R
tests/testthat/tests.brm.R
tests/testthat/tests.stancode.R

Implement more GP kernels

---

NEWS.md
R/numeric-helpers.R

Align step() with Stan and add int_step()

---

R/priorsense.R
man/create_priorsense_data.brmsfit.Rd

Fixes #1752 and does not seem to cause any issues.

allow newdata to pass to log_lik in create_priorsense_data

---

.github/workflows/R-CMD-check.yaml
DESCRIPTION

add colorspace to Suggests
