R/generics.R
Just a small typo fix in `hypothesis.brmsfit` help page.
=> fix small typo in `hypothesis` help page.

R/correlations.R, man/cor_ar.Rd, man/cor_ma.Rd
Hi Paul,
the default value for `p` in `cor_ar()` and for `q` in `cor_ma()` is 1.  The documentation inherited the defaults from `cor_arma()` although they are different.
With kind regards,
Peter.
=> Fix minor mistakes in the cor_ar() and cor_ma() documentation

vignettes/brms_missings.Rmd
Correct typos, and `\code{m}` was not displaying.
=> Correct minor errors in missing values vignette

R/emmeans-support.R, R/zzz.R, tests/testthat/tests.emmeans.R
This adds support for the **emmeans** package to the package code for **brms**. Because of the way it is dispatched, this code will override what already exists in the **emmeans** package.
This added code is essentially what is already provided in the **emmeans** package, but updated to avoid warnings, e.g., it uses `brmsterms` rather than `parse_bf`. It provides basic support for rather standard models, but not fancier ones, e.g. hurdle models. I would hope that by having this in your own package, you can add features to support those models too. I'd be happy to answer questions.
The contributed code consists of methods `recover_data.brmsfit` and `emm_basis.brmsfit`; added code in `zzz.R` to register these methods when **emmeans** is installed on the user's system; and a few tests on …
=> Added emmeans support

DESCRIPTION, R/backends.R, R/brm.R, man/brm.Rd
* Adds usage of new `show_messages` argument in CmdStanR's `$sample()` method
* Gets rid of deprecation warning from `cores` changing to `parallel_chains` in CmdStanR
* Use `cmdstanr::write_stan_tempfile()` for convenience
* Adds version requirement for CmdStanR (alternatively if you prefer we could add logic in the R code to not try to use `show_messages` for earlier versions of CmdStanR but that seemed messier) 
```r
fit <- brm(count ~ zAge, data = epilepsy, backend = "cmdstanr", refresh = 0, cores = 4)
Start sampling
Running MCMC with 4 parallel chains...
Chain 1 finished in 0.2 seconds.
Chain 2 finished in 0.2 seconds.
Chain 3 finished in 0.1 seconds.
Chain 4 finished in 0.1 seconds.
All 4 chains finished successfully.
Mean chain execution time: 0.2 seconds.
Total execution time: 0.2 …
```
=> CmdStanR updates

DESCRIPTION, R/backends.R
closes #981
* Bump cmdstanr version to 0.1.2 (now available via mc-stan.org/r-packages)
* Replace deprecated `write_stan_tempfile()` with `write_stan_file()`
=> write_stan_tempfile -> write_stan_file

R/emmeans.R
Hi Paul,
The small commit adds the number of chains to the `emmeans` method. This automatically propagates chain number to `emmeans` in case one requests the samples. The result is that the `emmeans` method behaves more similar than the other `emmeans` methods for MCMC samples.
As an example, take the following code:
```r
library("brms")
fit_warp <- brm(breaks ~ wool * tension, data = warpbreaks, 
chains = 2, iter = 1000)
library(emmeans)
str(as.mcmc(emmeans(fit_warp, "wool")))
```
The result from the current version gives an output without chain information.
```
NOTE: Results may be misleading due to involvement in interactions
'mcmc' num [1:1000, 1:2] 30.5 26.5 31.7 32 30.4 ...
- attr(*, "dimnames")=List of 2
..$ : chr [1:1000] "1" "2" "3" "4" ...
..$ : chr [1:2] "wool A" "wool B"
- …
```
=> add number of chains to emmeans method

R/emmeans.R, R/kfold.R, man/emmeans-brms-helpers.Rd, vignettes/brms_nonlinear.Rmd
This PR adds the option `dpar = "mean"` to the support methods for the **emmeans** package. When `emmeans()` or other package function is called with `dpar = "mean"`, we obtain the expectation of the posterior predictive distribution at each grid point, rather than one of the model parameters.
The implementation has two basic parts:
* In `recover_data.brmsfit`, we combine all the predictors involved in modeling all fixed-effect parameters, so that
the reference grid includes reference levels for all these predictors.
* In `emm_basis.brmsfit`, the posterior sample (`post.beta` slot) is obtained using `posterior_epred()`. 
The `bhat` and `V` slots are the column means and covariance matrix, and the `X` matrix is the identity.
Note that I also added a detail to the documentation, and …
=> Update to emmeans support: dpar = "mean"

R/stan-response.R
As covered in #1039 in more depth, this PR puts the intermediate calculations for the adjacent-category logit onto the log scale:
```
real acat_logit_lpmf(int y, real mu, real disc, vector thres) {
int nthres = num_elements(thres);
vector[nthres + 1] p = append_row(0, cumulative_sum(disc * (mu - thres)));
return p[y] - log_sum_exp(p);
}
```
=> Use log-scale calculations for adjacent-category logit likelihoods

R/backends.R
Dear @paul-buerkner ,
Many thanks for your great brms package! 
Since a few days, I encounter following warning:
```
Warning: UNRELIABLE VALUE: Future ('<none>') unexpectedly generated random
numbers without specifying argument '[future.]seed'. There is a risk that those
random numbers are not statistically sound and the overall results might be
invalid. To fix this, specify argument '[future.]seed', e.g. 'seed=TRUE'. This
ensures that proper, parallel-safe random numbers are produced via the L'Ecuyer-
CMRG method. To disable this check, use [future].seed=NULL, or set option
'future.rng.onMisuse' to "ignore".
```
I use the future package to run chains concurrently. This PR fixes this warning. This is the relevant news entry of the future package:
> Version: 1.19.0 [2020-09-19]
> 
> …
=> Set seed when calling future::future

NEWS.md, R/backends.R
This adds support for within-chain threading in the new version of `rstan >= 2.25 | Stan >= 2.25`. It has been tested with https://github.com/stan-dev/rstan/pull/887 and https://github.com/stan-dev/math/pull/2261.
A new `rsran` option `threads_per_chain` has been added to control the within-chain number of threads (`threads$threads`):
```r
rstan::rstan_options(threads_per_chain = threads$threads)
```
If the model is compiled with threading support, the number of threads to use in parallelized sections _within_ an MCMC chain (e.g., when using the `Stan` functions `reduce_sum()` or `map_rect()`). The actual number of CPU cores used is `chains * threads_per_chain` where `chains` is the number of parallel chains. For an example of using threading, see [Reduce Sum: A Minimal …
=> backends: rstan: Support within-chain threading with Stan >= 2.25

NEWS.md, R/stan-response.R
This PR moves the calculations in the ```cratio``` and ```sratio``` families to the log-scale for numerical stability. All link functions are updated:
- ```cloglog```
- ```logit```
- ```probit```
- ```probit_approx```
- ```cauchit```
There is (currently) no benefit for the ```probit``` family, but this will improve when ```rstan``` is updated and the ```std_normal_lcdf``` function is available, as that is coded for much more stable behaviour in the tails. There is also no benefit for the ```cauchit``` family.
Tests showing the improved stability (and equality with current implementation):
- [cloglog](https://gist.github.com/andrjohns/ef72bd1f9a4b6d9d0812a9df700fb3db)
- [logit](https://gist.github.com/andrjohns/52ba8ec20e4b2099dd3c974ef5cbb4ef)
- …
=> Move sratio & cratio functions to log-scale

inst/chunks/fun_gaussian_process.stan
Replace cov_exp_quad with gp_exp_quad_cov. Fixes #1089 This is safe to use with the cran version of rstan as well (https://github.com/stan-dev/stan/blob/StanHeaders_2.21/src/stan/lang/function_signatures.h#L543).
I checked the rest of the deprecated language features/functions and I did not find any additional ones.
There is a use of deprecated increment_log_prob and normal_log in one of the tests, but those are just part of tests and dont actually compile.
=> Replace deprecated cov_exp_quad

R/backends.R
Closes #1091. May also need to catch the development versions that don't support `threads_per_chain` (e.g., by checking if the option exists), but that's ok since they're likely used by experienced users, especially with threading and/or OpenCL.
=> Check if `rstan` supports `threads_per_chain`

R/prepare_predictions.R, man/prepare_predictions.Rd
Edits to the documentation for sample_new_levels as discussed here (https://discourse.mc-stan.org/t/understanding-sample-new-levels-uncertainty-gaussian-and-old-levels/7828/10) to improve clarity.
=> edits to doc for sample_new_levels parameter

R/misc.R
brms failed to install for users with older emmeans present because install.packages() by default does not update "Suggests" dependencies.
=> Add eemeans version check before registering methods .onLoad

DESCRIPTION, R/projpred.R
Smooth terms (`"sm"`; splines via `s()` and `t2()`) are already supported in `projpred`. This PR allows `get_refmodel()` to get the reference model structure with those terms.
The following simple example works fine:
```r
library(brms)
library(projpred)
dat <- mgcv::gamSim(1, n = 400, scale = 2)
fit0 <- brm(y ~ s(x0) + x1 + s(x2), data = dat)
refmod0 <- get_refmodel(fit0)
vs0 <- varsel(refmod0)
plot(vs0)
```
But, when combining smooth terms in an interaction term via `t2()`, `get_refmodel()` works fine but `varsel()` fails:
```r
fit1 <- brm(y ~ x1 + t2(x0, x2), data = dat)
refmod1 <- get_refmodel(fit1)
vs1 <- varsel(refmod1)
```
>Error in str2lang(x) : <text>:1:29: unexpected ','
1: . ~ 1 + t2(x0, x2) + x1 + x0,
^
Here's the traceback:
```
> traceback()
9: str2lang(x)
8: …
```
=> projpred: get_refmodel: Support smooth terms

R/backends.R, R/projpred.R, man/get_refmodel.brmsfit.Rd
The `cvfun` function is hardcoded here while a variant of it is maintained in `projpred::init_refmodel`. For example, a change like https://github.com/stan-dev/projpred/commit/6310b19a96c1e85ffbc89ff56a051bc2dadbcb95 breaks the hardcoded function here. This PR lets `projpred::init_refmodel` defines `cvfun` from `brmsfit` objects if it isn't passed in `...` (i.e., `cvfun = NULL` by default). Moreover, it will pass a custom function if set by the user.
=> projpred: Pass `cvfun` to `init_refmodel`

tests/testthat/helpers/inv_link_ordinal_fun.R, tests/testthat/tests.distributions.R
This PR is based on PR #1153, so it's better to merge #1153 first.
This PR refactors some unit tests involving the `inv_link_<ordinal_family>()` functions so that:
1. the unit tests are easier to read;
2. the `inv_link_<ordinal_family>_ch()` functions (note the `_ch` suffix) are also used for the matrix case (i.e., in the tests for the `d<ordinal_family>()` functions);
3. it's easier to swap the two implementations of the `inv_link_<ordinal_family>()` functions (see below).
Because of enumeration point 3, this PR also forms the basis for PR #1155 in which the two implementations of the `inv_link_<ordinal_family>()` functions are swapped (the original one and the one from the unit tests).
**EDIT:**
Insert the PR number (#1155) above.
=> Refactor unit tests for `inv_link_<ordinal_family>()`

R/distributions.R, tests/testthat/helpers/d_ordinal_sim.R, tests/testthat/helpers/inv_link_ordinal_fun.R, tests/testthat/helpers/inv_link_ordinal_sim.R, tests/testthat/tests.distributions.R
This PR is based on PR #1154, so it's better to merge #1154 first.
As suspected [here](https://github.com/paul-buerkner/brms/pull/1137#issuecomment-832596346) (enumeration point 2), the current unit tests for the `inv_link_<ordinal_family>()` functions do indeed provide a more efficient implementation of these `inv_link_<ordinal_family>()` functions. Here is my requested speed comparison:
```r
library(brms)
options(mc.cores = parallel::detectCores(logical = FALSE))
data(inhaler, package = "brms")
bfit_cumul <- brm(
formula = rating ~ period + carry + treat + (1 | subject),
data = inhaler,
family = cumulative(),
seed = 475064792
)
library(microbenchmark)
microbenchmark(epred_cumul <- posterior_epred(bfit_cumul),
times = 25)
bfit_sratio <- update(bfit_cumul, family = sratio()) …
```
=> Improve efficiency of the `inv_link_<ordinal_family>()` functions

DESCRIPTION
Here's the list of current NOTEs:
```r
Check: Rd cross-references
Result: NOTE
Undeclared packages ‘shiny’, ‘gtable’ in Rd xrefs
```
```r
Check: package dependencies
Result: NOTE
Package suggested but not available for checking: 'cmdstanr'
```
```r
Check: installed package size
Result: NOTE
installed size is 6.5Mb
sub-directories of 1Mb or more:
R 3.1Mb
doc 2.4Mb
```
The 1st one should be fixed by this PR.
@paul-buerkner Do you really need to suggest `cmdstanr` before it's released to CRAN?
I think the installed package size is hard to resolve.
=> Fix CRAN NOTEs

tests/local/tests.models_new.R
This test ensures that predictions for non-looped non-linear models are evaluated in a blocked way with the order of the data-set not being changed.
=> add test that non-looped non-linear models 

R/brmsformula.R, R/families.R, R/formula-ad.R, man/addition-terms.Rd, man/brmsformula.Rd, man/custom_family.Rd
This is a minor doc update to explain how to pass multiple vint or vreal terms and to further clarify the impact of setting `custom_family(type = )`.  I have not yet run roxygenise.  
While I think this is the only relevant place in the doc for this information, a potential problem is that it is not easily discoverable.  For example `?custom_family` provides a link to the doc for `stanvars`, but there's not trail of links to get through to the doc for `?brmsformula`.
Additionally, there are two things that I'd like to doc but I'm not sure where to put the doc:
* The important distinction between `custom_family(..., vars = vint1)` and `custom_family(..., vars = vint1[n])` that was a stumbling block for both me and @wds15.
* How multiple `vint` or `vreal` terms get matched to the arguments …
=> doc updates for custom families

R/projpred.R
This fixes the following issue:
```r
data("df_gaussian", package = "projpred")
dat <- cbind("y" = df_gaussian$y, as.data.frame(df_gaussian$x))
library(brms)
options(mc.cores = parallel::detectCores(logical = FALSE))
bfit <- brm(y ~ V1 + V2 + V3 + V4 + V5,
data = dat,
seed = 1140350788)
library(projpred)
refm <- get_refmodel(bfit)
prd <- predict(refm, dat)
str(prd)
```
With brms v2.16.1, that last line returns
```
num(0)
```
With the fix from this PR, that last line returns
```
num [1:100] -0.373 2.549 -0.032 -1.491 -2.386 ...
```
The reason for this issue is that in projpred v2.0.2 (the current CRAN version), `predict.refmodel()` does not expect `weights` or `offset` to be `NULL`. I have already fixed this in one of my projpred branches, but until this is merged into projpred's `master` …
=> Fix `.extract_model_data()`, e.g. in case of no offsets

R/projpred.R, man/get_refmodel.brmsfit.Rd
This fixes #1230: In the `get_refmodel.brmsfit()` docs, details concerning ignored arguments of `extract_model_data()` are added.
=> `get_refmodel.brmsfit()` docs: ignored arguments

R/backends.R
Variational inference with threading failed with `cmdstanr` since the `threads` argument was misnamed. 
Altered naming of the threads argument for matching algorithms, but left unmatching algorithms to fall through to the later `stop` command. You may prefer to handle the unmatching algorithms here too, or to provide a default via `else`.
=> Corrected passthrough of threads for VI

NEWS.md, R/kfold.R, R/projpred.R, man/get_refmodel.brmsfit.Rd
This is a "quick" fix for issue #1286 because it resolves the error described in #1286 (due to `allow_new_levels`), but it doesn't resolve the inconsistency between the reference model's linear predictors and the submodels' linear predictors described in stan-dev/projpred#268.
The first three commits (d47829399fb55015ad46ef9f69a575d6a9d740a4, ddcece60c8eda555087e8b4a1e17d2f3d44ffe3f, db89c178406339ae68124357fad50cade8da88d6) are not really related to the `allow_new_levels` issue; I stumbled across them while working on this. To see the issue of attaching brms (solved by commit db89c178406339ae68124357fad50cade8da88d6), consider the following reprex:
```r
set.seed(457211)
dat <- matrix(rnorm(41 * 2, sd = 0.4),
ncol = 2,
dimnames = list(NULL, paste0("X", 1:2)))
dat <- data.frame(dat) …
```
=> Quick fix for issue #1286 (and other changes for K-fold CV)

R/projpred.R
Sorry, I just realized that I have overseen something while making the switch from `kfold_seed` and `refprd_seed` to `brms_seed` in PR #1287. I did search for remaining occurrences of `kfold_seed` and `refprd_seed`, but that didn't prevent me from overseeing that more of them need to be replaced. And since that `refprd_seed` remnant got swallowed up by `projpred::init_refmodel()`'s ellipsis, it didn't produce an error in brms's `R CMD check`.
=> Fix PR #1287

R/distributions.R, R/projpred.R, tests/testthat/helpers/inv_link_categorical_ch.R, tests/testthat/helpers/link_categorical_ch.R, tests/testthat/tests.distributions.R
This PR should perform the final changes which are necessary to support the augmented-data projection in projpred. Note that I partly reverted some of my changes in `get_refmodel.brmsfit()` introduced earlier (by PR #1159). The reason is that I found a more elegant way of handling the preparations for the augmented-data projection, namely by using a wrapper function for the user-specified `ref_predfun` within **projpred**. (Btw, this wrapper also handles the subtraction of the offsets, which is why we didn't have to subtract offsets in the brms-specific `ref_predfun` in PR #1287.) Sorry for the changes in `get_refmodel.brmsfit()` introduced earlier which are now partly reverted. But I think the new handling is much better, especially because it requires much less changes to **brms** and …
=> Support augmented-data projection in projpred

R/projpred.R
I'm really sorry, but I already found two bugs for the `categorical()` family in my code from PR #1292. This PR fixes these bugs (see the commit messages for details). The new common `ref_predfun` definition also avoids redundancies (in fact, these redundancies introduced the `t()` bug).
=> Fix PR #1292

R/backends.R, R/make_stancode.R, tests/testthat/tests.make_stancode.R
See inline comments for a bit of detail. 
I didn't add any tests yet, will wait if you are fine with this first, I used the following to test this:
```r
library("brms")
data("kidney", package = "brms")
head(kidney, n = 3)
fit1 <- brm(formula = time | cens(censored) ~ age * sex + disease 
+ (1 + age | patient), 
data = kidney, family = lognormal(),
backend = "cmdstanr")
```
This produces warnings with 2.29, but not on the PR branch.
Fixes #1301
=> Canonicalize model code for CmdStan >= 2.29.0

R/projpred.R
This fixes what must have been a long-standing bug (in particular, it must have already existed back then where projpred's default `ref_predfun` was used): In the `ref_predfun`'s `posterior_linpred()` call, the `resp` argument was not included. So the following failed because `posterior_linpred()` returned an array of linear predictors (third margin corresponding to the responses):
```r
library(brms)
options(mc.cores = parallel::detectCores())
data(keeley, package = "piecewiseSEM")
keeley_fit <- brm(
bf(rich ~ firesev + cover) + bf(cover ~ firesev) + set_rescor(FALSE),
data = keeley,
seed = 9512,
refresh = 0
)
library(projpred)
refm <- get_refmodel(keeley_fit, resp = "rich", brms_seed = 8532)
```
Sorry that this escaped my attention when I defined the custom `ref_predfun` in …
=> `get_refmodel.brmsfit()`: Add `resp` in `posterior_linpred()`

R/projpred.R
This fixes a bug in `get_refmodel.brmsfit()` for Bernoulli models having a `factor`-like response:
```r
data("df_gaussian", package = "projpred")
dat <- data.frame(y = df_gaussian$y, df_gaussian$x)
set.seed(457211)
icpt <- -0.42
dat$y <- rbinom(nrow(dat), size = 1,
prob = binomial()$linkinv(icpt + 0.8 * dat$X1))
dat$y <- as.factor(paste0("resp", dat$y))
library(brms)
options(mc.cores = parallel::detectCores(logical = FALSE))
fit <- brm(y ~ X1 + X2 + X3 + X4 + X5,
data = dat,
family = bernoulli(),
control = list(adapt_delta = 0.95,
max_treedepth = 15L),
refresh = 0,
seed = 1140350788)
library(projpred)
refm <- get_refmodel(fit)
d_test_dummy <- list(type = "test",
y = refm$y,
test_points = seq_along(refm$y),
data = refm$fetch_data(),
weights = refm$wobs,
offset = refm$offset)
vs <- …
```
=> projpred: Make `extract_model_data()` return a factor `y` if necessary

NEWS.md, R/pp_check.R, tests/local/setup_local_tests.R, tests/local/tests.models_new.R
Hopefully addresses https://github.com/paul-buerkner/brms/issues/1326.
The diff got a bit confused, it's mostly just moving the `ppc_arg` assignments, like `group,lw,x,psis` above the censor check, then subsetting them there if they are used.
Also allows censored values for the `type = "km_overlay"` plot (https://mc-stan.org/bayesplot/reference/PPC-censoring.html).
`sysdata.rda` just has `brms:::brmsfit_example7` included for the censored tests, I didn't re-run the other example fits.
Re-running some of the examples in the issue:
``` r
library(brms)
data(kidney)
fit <- brm(
formula = time | cens(censored) ~ age * sex + disease + (1 | patient),
data = kidney, family = lognormal(),
prior = c(set_prior("normal(0, 5)", class = "b"),
set_prior("cauchy(0, 2)", class = "sd")),
seed = 0, warmup = …
```
=> Support all pp_check types for censored y

doc/brms_families.Rmd, vignettes/brms_families.Rmd
I guess there is a typo in the density of the skew normal distribution shown in the "Parameterization of Response Distributions in brms" vignette.
Note: This PR is probably incomplete. I just "blindly" fixed the typo in the .Rmd files (of which there seem to be two). I did not rebuild the pkgdown site, for example.
=> Fix typo in the density of the skew normal distribution

R/projpred.R
In PR #1314, I didn't realize that your changes are not quite equivalent to my original code: The check which is now performed in lines https://github.com/paul-buerkner/brms/blob/6b3c626672a1bf25514da4b7268dedfe7add9de0/R/projpred.R#L218-L224 of `brms:::.extract_model_data()` fails for non-factor responses (of a categorical or ordinal model) if `newdata` does not contain all unique values from the original dataset. That's why I performed that check in `get_refmodel.brmsfit()` based on the original dataset (lines https://github.com/paul-buerkner/brms/blob/55490722db4346fe6a3ed510f4054e584d6f5ca6/R/projpred.R#L119-L122), but in [this comment](https://github.com/paul-buerkner/brms/pull/1314#issuecomment-1065947185) I forgot about non-factor responses. Sorry for that.
With this PR, I decided …
=> Fix PR #1314

DESCRIPTION, R/update.R, man/AsymLaplace.Rd, man/BetaBinomial.Rd, man/Dirichlet.Rd, man/ExGaussian.Rd, man/Frechet.Rd, man/GenExtremeValue.Rd, man/Hurdle.Rd, man/InvGaussian.Rd, man/LogisticNormal.Rd, man/MultiNormal.Rd, man/MultiStudentT.Rd, man/Shifted_Lognormal.Rd, man/SkewNormal.Rd, man/VonMises.Rd, man/Wiener.Rd, man/ZeroInflated.Rd, man/update.brmsfit.Rd
This documents how cmdstanr's option `cmdstanr_write_stan_file_dir` can be used to avoid a recompilation when calling `update.brmsfit()` on a cmdstanr-backend fit in a fresh R session, thereby solving #1135 completely (without the need for further changes in cmdstanr).
I wasn't sure how to clean up the files which are currently created permanently by the new example (two `model_<hash>.stan` files and one `model_<hash>(.exe)` executable). Deleting all regexp'ed `^model_.*\\.stan` files and corresponding executables after running the example would be dangerous. Less dangerous alternatives would be to
1. diff the list of files before and after running the new example and delete all files created in between;
2. extend the `if (!file.exists("fit_cmdstanr.rds"))` condition to only run the new …
=> Document option `cmdstanr_write_stan_file_dir` for `update.brmsfit()`

R/kfold.R, R/update.R, man/kfold.brmsfit.Rd, man/update.brmsfit.Rd
This documents how cmdstanr's option `cmdstanr_write_stan_file_dir` can be used to avoid recompilations when calling `kfold.brmsfit()` on a cmdstanr-backend fit in a fresh R session, thereby solving #1340 (in the same way as #1135 has been documented by #1374).
=> Document option `cmdstanr_write_stan_file_dir` for `kfold.brmsfit()`

R/kfold.R, brms.Rproj, man/kfold.brmsfit.Rd
This fixes the documentation for `...` in `kfold.brmsfit()` because `kfold.brmsfit()` allows to pass arguments to `brm()` (see <https://github.com/paul-buerkner/brms/issues/1378#issue-1300775618>).
Here, I have copied the `...` documentation from `brm_multiple()` instead of inheriting it from `loo.brmsfit()`. But I'm not sure if it actually contains everything that is needed for `...` in `kfold.brmsfit()`. You might have to mention more functions (apart from `brm()`) that can get arguments from `...`.
=> Fix documentation for `...` in `kfold.brmsfit()`

R/projpred.R
This is just a collection of three minor improvements for `get_refmodel.brmsfit()`.
Note that a local `R CMD check` gave:
```
❯ checking Rd \usage sections ... WARNING
Undocumented arguments in documentation object 'Wiener'
‘x’
Functions with \usage entries need to have the appropriate \alias
entries, and all their arguments documented.
The \usage entries must correspond to syntactically valid R code.
See chapter ‘Writing R documentation files’ in the ‘Writing R
Extensions’ manual.
```
and the following test failure:
```
── Error (tests.make_stancode.R:470:3): self-defined functions appear in the Stan code ──
Error in `rstan::stanc(model_code = model, ...)`: failed to parse Stan model 'model' due to the above error.
```
However, after commenting lines …
=> Minor improvements for `get_refmodel.brmsfit()`

.github/workflows/R-CMD-check.yaml, DESCRIPTION, R/backends.R
This PR updates the Stan model canonicalisation process to be fully delegated to `cmdstanr`, rather than manually calling `stanc`. This is to allow for compatibility with the new WSL functionality in `cmdstanr`, (which is unfortunately not currently compatible with `brms` due to the manual `stanc` call)
Let me know if I can add any other clarifications/changes here!
Cheers,
Andrew
=> Fully delegate canonicalisation to cmdstanr

R/brmsfit-helpers.R, R/brmsformula.R, R/distributions.R, R/numeric-helpers.R, man/brmsformula.Rd, tests/testthat/helpers/inv_link_categorical_ch.R
While working on extended unit tests for projpred's augmented-data projection, I realized that `inv_link_categorical([...], log = FALSE)` sometimes returned `NaN`. This PR fixes that by always calling `log_softmax()` and exponentiating afterwards (instead of calling `softmax()` directly).
Reprex (supplying the data as a [CSV](https://github.com/paul-buerkner/brms/files/9482419/softmax_arr_fail.csv) was the easiest way for this):
```r
etas_i <- as.matrix(read.csv("softmax_arr_fail.csv"))
mus_i_direct <- brms:::inv_link_categorical(etas_i)
sum(is.na(mus_i_direct))
mus_i_indirect <- exp(brms:::inv_link_categorical(etas_i, log = TRUE))
sum(is.na(mus_i_indirect))
all.equal(mus_i_direct[!is.na(mus_i_direct)],
mus_i_indirect[!is.na(mus_i_direct)],
tolerance = 1e1 * .Machine$double.eps)
etas_i <- …
```
=> Fix numerical issue in `softmax()`

NEWS.md, R/projpred.R, man/get_refmodel.brmsfit.Rd
I realized that in #1451, I could have checked the projpred version that is required for the latent projection directly in the code. Sorry, I have implemented this now (and also added corresponding documentation at argument `latent`; #1451 did so only in the `NEWS` entry).
=> Check projpred version for latent projection

DESCRIPTION, NEWS.md, R/projpred.R, man/get_refmodel.brmsfit.Rd
This fixes issue #1457. See the commit messages for details. If you don't want to increase the version number, you can revert that of course.
I have also added a `TODO` comment in [this line](https://github.com/fweber144/brms/blob/79d55b1861cd252d832913d286eb7ec77952661b/R/projpred.R#L268) because I experienced a slight inconsistency while testing this fix: If *weights* (i.e., from `resp_weights()`) are missing in `newdata` (and listed in `req_vars`), no error is triggered, but such an error is triggered if *numbers of trials* (i.e., from `resp_trials()`) are missing in `newdata` (and listed in `req_vars`). Already from a conceptual point of view, I think it would be desirable to also throw an error if weights are missing. Tell me if you need a reprex for this (but I think this would be a …
=> Fix #1457 (projpred `newdata` requiring more variables than necessary)

NEWS.md, R/projpred.R
This is an amendment for #1459. I realized that `check_response = TRUE` has no effect if `req_vars = character()`, so we need to set `req_vars` to the response variable.
=> Amend #1459

R/brm.R, R/brm_multiple.R, R/brmsfit-helpers.R, man/brm.Rd, man/brm_multiple.Rd
RDS objects containing brmsfit objects can be quite large depending on the model. Currently, brms uses saveRDS's default compression, gzip, to save models to disk. However, saveRDS also supports xz and bzip2. I found that simply using xz instead of gzip can result in a dramatic reduction in needed disk space, tested by reading in a saved model and just reexporting it with `saveRDS(object, file, compress = "xz")`. While the write process is noticeably slower, I tested with two models and observed these reductions in file size:
- 141 MB -> 73 MB
- 395 MB -> 205 MB
This reduced the model sizes to a little over half of the original size, which seems like a pretty good savings.
This pull request adds a `compress` parameter to `brm` and `write_brmsfit` that gets passed along to `saveRDS` to …
=> Add compress parameter to brm and write_brmsfit

NEWS.md, R/projpred.R, man/get_refmodel.brmsfit.Rd
This fixes a minor bug in PRNG usage of `get_refmodel.brmsfit()`: The PRNG state should be reset upon exit only if the user-supplied seed is not `NULL`. See the `NEWS.md` entry from 8db0bbde83033b4495438da43be7ba23459766b4 for details.
In principle, I would also recommend to replace `brms_seed = NULL` with `brms_seed = NA` (i.e., changing the default but also replacing `is.null(brms_seed)` with `is.na(brms_seed)` within the function—although length 1 would probably have to be asserted for `NA`—and adapting the code for `brms_seed_k` accordingly) because `NULL` has a special meaning for `set.seed()`'s argument `seed`, namely to generate completely unreproducible results (which might sometimes be desired by users). However, it seems like within brms, `NA` has a special meaning for seed …
=> projpred-related seed fix and docs/NEWS

R/data-helpers.R, R/make_standata.R, R/projpred.R
When `posterior_predict` is called with `newdata`, `validate_newdata` will be called and this represents a non-trivial amount of the total execution time. Advanced users may want to skip this step when they know their data already has the proper structure.
As there are different kinds of validation functions in the package, the proposed argument name is `skip_validate_data`.
```r
library(brms)
fit <- brm(time | cens(censored) ~ age + sex + (1 + age || patient),
data = kidney, family = "exponential", init = "0",
backend = "cmdstanr")
microbenchmark::microbenchmark(
posterior_predict(fit, newdata = fit$data),
posterior_predict(fit, newdata = fit$data, skip_validate_data = TRUE)
)
```
The change is made for both `current_data` and `current_data2` and should work without issue when passed via …
=> Allow data validation to be skipped to improve `posterior_predict` performance with `newdata`

R/projpred.R
This reverts the recent addition of the ellipsis (see #1521) to `current_data()` calls related to projpred. There are two such calls: One in `get_refmodel.brmsfit()` (when getting `data`) and one in `.extract_model_data()`. Apart from the fact that #1521 didn't document the extended use of `get_refmodel.brmsfit()`'s ellipsis, I also think that a double use of that ellipsis is dangerous for the future (because more arguments might be added to downstream functions either in projpred or in brms, increasing the risk of conflicts). In `.extract_model_data()`, the ellipsis can be removed because projpred never calls `extract_model_data()` with arguments other than those specified in projpred's documentation (in particular, the user doesn't have the possibility to pass arguments to …
=> Revert some ellipses from #1521

R/projpred.R
This sets `called_from_cvrefbuilder = TRUE` within `get_refmodel.brmsfit()`'s `cvrefbuilder` function to suppress some warnings when building the fold-wise reference model objects (so far, argument `called_from_cvrefbuilder` only exists in projpred's current development version, but setting this argument within brms already now doesn't harm as unnecessary extra arguments are swallowed up by `projpred::init_refmodel()`).
=> Set `called_from_cvrefbuilder = TRUE` within `get_refmodel.brmsfit()`'s `cvrefbuilder` function

R/backends.R
Updates the `silent` -> `show_messages`,`show_exceptions` translation for `cmdstanr` to the following mapping:
- `silent=0` suppress nothing (`show_messages=TRUE, show_exceptions=TRUE`)
- `silent=1` suppress only exceptions (`show_messages=TRUE, show_exceptions=FALSE`)
- `silent=2` suppress messages and exceptions (`show_messages=FALSE, show_exceptions = FALSE`)
=> Update translation of silent argument to fix cmdstanr breakage

inst/chunks/fun_scale_r_cor_by.stan, inst/chunks/fun_scale_r_cor_by_cov.stan
In order to fix #1562 I adjusted to the new array notation:
- "inst/chunks/fun_scale_r_cor_by.stan"
- "inst/chunks/fun_scale_r_cor_by_cov.stan"
This fixes my problem. I couldn't test whether this creates issues with the RStan version on CRAN, as I have a newer version than that.
Also note that a quick search in the repo indicates there's a few additional places where the old type[] notation is still used: https://github.com/search?q=repo%3Apaul-buerkner%2Fbrms+%22int%5B%5D%22&type=code
=> second attempt to fix #1562

R/posterior_samples.R
Based on Stan Discourse, deprecation info was missing from as.mcmc doc https://discourse.mc-stan.org/t/as-mcmc-function-deprecated/33507
=> Add deprecation info to as.mcmc doc

R/projpred.R, man/get_refmodel.brmsfit.Rd
This PR adds warnings that arguments `wrhs` and `orhs` are currently ignored by `.extract_model_data()` (the workhorse function for `extract_model_data()` defined in `get_refmodel.brmsfit()`). This is relevant for `projpred::proj_linpred()`, `projpred::proj_predict()`, and `projpred:::predict.refmodel()`: When using an rstanarm reference model, it would be possible to specify weights and offsets in these 3 functions via arguments `weightsnew` and `offsetnew`, respectively. When using a brms reference model, these arguments are ignored (weights and offsets are fetched from `newdata`, as brms does at other places, too). So far, this has only been documented at `?get_refmodel.brmsfit`. With this PR, warnings are thrown to increase awareness.
Illustration:
```r
data("df_gaussian", package = …
```
=> `.extract_model_data()`: Warn that arguments `wrhs` and `orhs` are ignored

R/pp_check.R
Add more pp_check types in aps_types, that by default should use all draws
=> Add more pp_check types in aps_types

R/backends.R
This is a very minor change to the read_csv_as_stanfit function. It adds a check if csfit$inv_metric is not an empty list before reading in that information. This is rarely needed, but I am working on a checkpointing mechanism, and sometimes we read in incomplete warmup draws. In that case the current function fails because csfit$inv_metric[[i]] gives an error, because inv_metric is an empty list().
=> Allow read_csv_as_stanfit to work when inv_metric is not recorded

R/loo.R, R/loo_moment_match.R, man/loo.brmsfit.Rd, man/loo_moment_match.brmsfit.Rd
Small updates to doc. I decided to keep the k_threshold argument default unchanged (0.7), as here it specifically controls for which observations to run moment_matching or reloo, but loo recommendations has a new recommendation if the sample size specific threshold is <0.7 and there are Pareto k's exceeding that threshold. Unfortunately, `ps_khat_threshold()` is not yet exported in `loo` or `posterior` so had to copy that.
EDIT:fixes #1606
=> update doc and loo recommendations

R/family-lists.R, tests/testthat/tests.stancode.R
Closes #1631 by placing a student_t(1, 0, 1) prior on mu in the von_mises family when a tan_half link is used. This corresponds to a uniform prior over the constrained scale from -pi to pi.
The family-specific prior feature you implemented is really neat and made this super easy!
For what is worth, in my testing the prior change only had a meaningfull effects for very low numbers of observations and low precision (kappa) - otherwise results were pretty much identical.
This only affects the prior for the tan-half link - should the identity link prior be left as is? the current prior has a slight bump at 0, but its otherwise unimodal and weakly informative.
=> change default prior for von_mises mu tan_half link

R/backends.R
Reported by @ave, using `cmdstanr` backend is giving error in some cases:
```
Error in getClass(Class, where = topenv(parent.frame())) : 
“cxxdso” is not a defined class
```
Which is caused by the CSV processing attempting to use a class from the `rstan` package when it's not loaded. This PR updates the class lookup to specify that it should be found in `rstan`
=> Fix creating stanfit from csv when rstan not loaded

R/family-lists.R
After the change for #1633 I got an error that file "fun_von_mises.stan" could not be found. There was a left over include statement in the .family_von_mises() function. Removing it fixes the problem.
=> remove outdated include statement

R/brm.R, man/brm.Rd
Changes the default `brm(iter = 2000)` to `brm(iter = getOption("brms.iter", 2000))` (#1705) & revises associated documentation.
I tested this locally using examples in README.Rmd, but did not add tests because other similar arguments in `brm()` are not tested either.
Going forward it might make sense to think about using `options()` for e.g. `brm(control = <x>)` and others.
=> Use brms.iter option (#1705)

R/loo_predict.R
There is a misplaced paren in .loo_R2 causing wrong results. 
I first noticed discrepancy between manually computed point estimate and the distribution, then discrepancy compared to `bayesboot` and after 30mins of staring found the misplaced paren.
=> fix misplaced paren in .loo_R2

R/bayes_R2.R, R/loo_predict.R
Some fixes for loo_R2 doc and updated reference for Bayesian-R2
=> R2 doc improvements

R/brmsframe.R, R/data-predictor.R
Storing and re-using the originally computed boundary factor `L` will ensure that predictions for new covariate values work appropriately when predicting from approximate GPs
=> store original bounday factor L for approximate GPs

R/stan-predictor.R, tests/testthat/tests.stancode.R
Hi Paul,
I'm sorry to bother you with more on this prior-weights functionality from #1719. In applying this functionality to a different dataset from the 'survey' package, I realized there was a problem in the Stan code I wrote for this, linked here:
https://github.com/paul-buerkner/brms/blob/c741df7b008a9fccfff1b4d04a8102e0e8e6c1d7/R/stan-predictor.R#L641
https://github.com/paul-buerkner/brms/blob/c741df7b008a9fccfff1b4d04a8102e0e8e6c1d7/R/stan-predictor.R#L739
The problem is that `std_normal_lpdf()` function in Stan evaluates to a scalar, not a vector. So multiplying its output by the weights vector is incorrect. Instead, the code should have specified a loop over each group, adding the weights and the likelihood contribution from each group separately. 
This small PR fixes that issue …
=> Fix PW stan code.

DESCRIPTION, vignettes/brms_customfamilies.Rmd, vignettes/brms_distreg.Rmd, vignettes/brms_missings.Rmd, vignettes/brms_monotonic.Rmd, vignettes/brms_multivariate.Rmd, vignettes/brms_nonlinear.Rmd, vignettes/brms_phylogenetics.Rmd, vignettes/brms_threading.Rmd
I noticed that the brms package size is quite large, which is due to the rendered vignettes to a large extent. The proposed changes implement best practices I have come to learn on the net. The trick implemented uses the pngquant engine to compress the plots substantially. For example, the non-linear vignette has a size of 580 kb with the released version of brms while the version rendered with the changes on this PR reduces this to just 164 kb.
As I lack some dependencies to build the entire package, I can't report the total reduction of the final package (currently about 4MB), but I'd expect that the size will go down quite a bit. So please, do make a check to build the package and compare the gains before merging.
Given on how many servers the R package is replicated to, I'd guess that …
=> compress plots in vignettes

NEWS.md, R/backends.R, R/priors.R, tests/testthat/tests.brmsfit-methods.R, tests/testthat/tests.distributions.R, tests/testthat/tests.emmeans.R, tests/testthat/tests.log_lik.R, tests/testthat/tests.posterior_predict.R, tests/testthat/tests.priorsense.R, tests/testthat/tests.read_csv_as_stanfit.R, tests/testthat/tests.standata.R
I searched the rstan codebase for any cases where they accessed `@stan_args$control` for values and I made sure those fields were populated during `read_csv_as_stanfit()`. Those fields were `adapt_delta` and `max_treedepth`.
I also fixed a failing bayesplot test and added more `skip_if_not_installed()` for Suggested packages that I did not have installed. 
Closes #1767
=> update read_csv_as_stanfit() to work with rstan::get_hmc_diagnostics()

R/hypothesis.R
Clarified that seed argument only affects point hypotheses that scope over more than one parameter. I also reordered that clarifications about the Savage-Dickey method under Details a bit. Finally, as suggested by Paul, I clarified that users should consider bridge sampling instead of the denisty_ratio method.
See conversation at https://github.com/paul-buerkner/brms/issues/1750#issuecomment-2850200193.
=> Clarification of role of seed argument for point hypotheses

R/pp_check.R
`ppc_loo_pit_ecdf` was recently added to `bayesplot`. This PR will add "loo_pit_ecdf" to aps_types, so that by default all posterior draws are used to make the plot. Otherwise, using github version of `bayesplot` `pp_check(fit, type="loo_pit_ecdf")` works already
=> add loo_pit_ecdf to aps_types

DESCRIPTION
Update testthat version in Suggests to >= 3.1.9, since recent tests depend on it.
Closes #1796.
=> require testthat (>= 3.1.9) in Suggests

R/summary.R, tests/testthat/tests.brmsfit-helpers.R
summary.brmsfit function gives error when it does not have object$fim@sim 
closes #1795
```R
library(brms)
data_model1 <- data.frame(y = rnorm(10), x = rnorm(10))
fake_fit <- brm(y ~ x, data = data_model1, empty = TRUE)
summary(fake_fit )
Error in summary.brmsfit(x, ...) : 
trying to get slot "sim" from an object of a basic class ("NULL") with no slots
Called from: summary.brmsfit(x, ...)
```
=> fix for summary.brmsfit when it does not have fit property

R/misc.R, tests/testthat/tests.stop2.R
modifies existing stop2 function with rlang::abort call
```r
stop2 <- function(message = "", ..., .subclass = NULL,
call = NULL, .envir = parent.frame()) {
if (is.null(call)) {
call <- rlang::caller_call()
}
rlang::abort(
message   = glue::glue(message, ..., .envir = .envir),
.subclass = c(.subclass, "brms_error"),
call      = call
)
}
```
closes #1802
=> Adds rlang abort to stop2

DESCRIPTION, R/brm.R, R/brm_multiple.R, R/kfold.R, R/reloo.R, man-roxygen/parallelization.R, man/brm.Rd, man/brm_multiple.Rd, man/hypothesis.brmsfit.Rd, man/kfold.brmsfit.Rd, man/reloo.brmsfit.Rd
Adds instructions for users how to consider parallelisation and suggests the use of mirai via future.mirai as it enables to push companions to a computer cluster.
Optionally we could also add a link to https://opensource.nibr.com/bamdd/src/03b_parallel.html where these things are detailed, but that is not yet in the text.
=> extend documentation on parallelisation and suggest use of mirai via future.mirai
